### ISSUE TITLE
org.xml.sax.SAXParseException when converting Abbyy Cloud OCR XML 

### ISSUE THREAD

**Issue by cboulanger** [PRImA-Research-Lab/prima-page-converter#19]
I am using https://github.com/UB-Mannheim/ocr-fileformat which includes the prima-page-converter.

Given [this file](https://files.gitter.im/609272e76da03739847bdbf8/s5U8/10.1515_zfrs-1980-0101.xml) (also saved [here](https://gist.github.com/cboulanger/1437cd051fdf6a304408dfce48056332) in prettified and abbreviated form) and the command 

```
docker run --rm -it -v "$PWD":/data ubma/ocr-fileformat ocr-transform abbyy page 10.1515_zfrs-1980-0101.xml 10.1515_zfrs-1980-0101.page.xml
```

I get [this error message](https://gist.github.com/cboulanger/03023881c65361b88dd4b20e9ae481ce) and [this (prettified) output](https://gist.github.com/cboulanger/ec51e86e224ad9b679aaec10ff2cbcea). 

I am not familiar with the PAGEXML format, but I see very little of original Abbyy XML information in the result - how much of it does the current converter preserve?

Thank you.

**Comment by cboulanger** [comment]
Here's the error message so you don't need to look it up in the gist:
```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:630)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:686)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2181)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:578)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at org.primaresearch.io.xml.XmlValidator.getSchema(XmlValidator.java:55)
	at org.primaresearch.dla.page.io.xml.XmlPageReader.createMainParser(XmlPageReader.java:82)
	at org.primaresearch.dla.page.io.xml.XmlPageReader.parse(XmlPageReader.java:176)
	at org.primaresearch.dla.page.io.xml.XmlPageReader.read(XmlPageReader.java:130)
	at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.readPage(PageXmlInputOutput.java:212)
	at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:230)
	at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:161)
```

**Comment by cboulanger** [comment]
I also tried a [version of the Abbyy file format without variants](https://github.com/PRImA-Research-Lab/prima-page-converter/files/6492851/10.1515_zfrs-1980-0101.xml.txt), which produced  [this output](https://github.com/PRImA-Research-Lab/prima-page-converter/files/6492855/10.1515_zfrs-1980-0101.page.xml.txt) and the identical error (I had to add a `.txt` suffix to the xml files as GitHub wouldn't let me upload `.xml` files, which is weird).

**Comment by maxnth** [comment]
The exceptions seems to be the same one that one of my colleagues encountered as well (see: #8).

My guess would be that this is caused by the schema location in the Abbyy XML redirecting from `http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml` to `https://fr7.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml`. 

InputStream (at https://github.com/PRImA-Research-Lab/prima-core-libs/blob/1f087a4378f58a34c83176ab0ffb620dd8b78f2d/java/PrimaIo/src/org/primaresearch/io/xml/XmlValidator.java#L65-L66) then probably fails to get the actual content of the schema and therefore `org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.` gets raised when trying to create a new schema from it.

Using the following function to retrieve the "actual final" URL allowed me to parse the ABBYY XML file, create a new `Schema` with `schemaFactory` and validate the file. 
```Java
public static URL retrieveFinalURL(String urlString) throws IOException {
  URL url = new URL(urlString);
  URLConnection urlConnection = url.openConnection();
  
  if(!(urlConnection instanceof JarURLConnection)){
	  HttpURLConnection con = (HttpURLConnection) urlConnection;
	  con.setInstanceFollowRedirects(false);
	  con.connect();
	  con.getInputStream();
  
	  if (con.getResponseCode() == HttpURLConnection.HTTP_MOVED_PERM || con.getResponseCode() == HttpURLConnection.HTTP_MOVED_TEMP) {
		  String redirectUrl = con.getHeaderField("Location");
		  return retrieveFinalURL(redirectUrl);
	  }
  }

return url;
}
```
I'm not sure if it's wise to just "blindly" follow redirects from a security standpoint though (especially because something like this is probably an edge case (?))

Edit: I created a [fork](https://github.com/maxnth/prima-core-libs) with the changes.

**Comment by cboulanger** [comment]
Thanks for looking into this - I hadn't thought of looking into the closed issues: but it looks like the fix didn't fully resolve the issue. I cannot say much on the security implications of a forged XSLT document, but maybe outputting a big warning would be preferrably over breaking the conversion completely?

**Comment by maxnth** [comment]
>but maybe outputting a big warning would be preferrably over breaking the conversion completely?

IIUC the conversion doesn't really break when the exception is raised, only the validation of the Abbyy files breaks. I ran the conversion with and without my "fix" for fetching redirected schema locations (which in turn doesn't raise any exception during conversion) and the results are completely identical. 
I'd guess that everything that is missing after the conversion (and therefore appears broken) just isn't implemented in https://github.com/PRImA-Research-Lab/prima-core-libs/blob/master/java/PrimaDla/src/org/primaresearch/dla/page/io/xml/sax/SaxPageHandler_AbbyyFineReader10.java (?) yet.
