### ISSUE TITLE
SAXParseException: Premature end of file

### ISSUE THREAD

**Issue by chaddy314** [PRImA-Research-Lab/prima-page-converter#8]
I'm getting this Exception when trying to convert abbyy.xml files to page-xml.
To reproduce the Error you can use the sample DemoImage1_ABBYY_Basic.xml from the [official Abbyy website](https://abbyy.technology/_media/en:features:ocr:abbyy_xml_sample_collection.zip).

command: `java -jar PageConverter.jar -source-xml DemoImage1_ABBYY_Basic.xml -target-xml abbyy_2_page_test.xml`

Stacktrace:
``` bash
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1013)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:640)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:696)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2206)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:587)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:576)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:276)
	at java.xml/javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:669)
	at org.primaresearch.io.xml.XmlValidator.getSchema(XmlValidator.java:55)
	at org.primaresearch.dla.page.io.xml.XmlPageReader.createMainParser(XmlPageReader.java:87)
	at org.primaresearch.dla.page.io.xml.XmlPageReader.parse(XmlPageReader.java:203)
	at org.primaresearch.dla.page.io.xml.XmlPageReader.read(XmlPageReader.java:135)
	at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.readPage(PageXmlInputOutput.java:209)
	at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:139)
	at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:94)
```

Found this (maybe relevant) [issue on stackoverflow](https://stackoverflow.com/questions/11114665/org-xml-sax-saxparseexception-premature-end-of-file-for-valid-xml/31953108) and looked into the prima-core-libs, but could not identify the problem here.

Java version: 11.0.4
OS: Ubuntu 18.04.3 LTS x86_64

Thanks in advance,
Kevin Chadbourne

**Comment by chris1010010** [comment]
Can you confirm that the conversion still works? It does for me. I get the exception though. For some reason it doesn't like ABBYY's online schema file. So it doesn't validate, but it still converts.

**Comment by chaddy314** [comment]
It does create the file, but still at least misses the text.
Here are the [XML files](https://github.com/PRImA-Research-Lab/prima-page-converter/files/3541648/abby2page.zip) I used/that were created.

**Comment by chris1010010** [comment]
Hmm, I just had a look at the code - it's very experimental!!!
If you have access to a Windows machine, I recommend using our other converter tool:
[PageConverterAndValidator](https://www.primaresearch.org/tools/PAGEConverterValidator)
That one is more mature regarding FR XML.

**Comment by chris1010010** [comment]
I improved the FR XML handler a little bit (text content and text lines). The next version will be released soon.
